on:
  push:
  schedule:
  - cron: '0 * */1 * *'

jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Tree
      uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install python3-venv cssmin
        mkdir env
        python3 -m venv env
        source env/bin/activate
        python -m pip install tqdm jinja2==2.11.3 PyGithub minify-html
        ./build.sh
        cssmin > dist/theme.css.min < dist/theme.css
        mv dist/theme.css.min dist/theme.css
        echo "xemu.app" > dist/CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true

